In [1]:
import sys
sys.version

'3.8.19 (default, Mar 20 2024, 19:55:45) [MSC v.1916 64 bit (AMD64)]'

In [2]:
import cv2
print(" cv version",cv2.__version__)

 cv version 4.10.0


In [3]:
import cv2
image=cv2.imread(r"C:\\Users\\Mr\\\Downloads\Video\\New folder\\girl.jpeg")

In [5]:
image = cv2.imread(r"C:\Users\Mr\Downloads\Video\New folder\girl.jpeg")


In [6]:
if image is not None:
    cv2.imshow('beautiful girl', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Image not loaded.")

In [7]:
image = cv2.imread(r"C:\Users\Mr\Downloads\Video\New folder\girl.jpeg")

img=cv2.resize(image,(300,200))

In [8]:
cv2.imshow("my pic",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import os
imag_name=os.listdir("C:\\Users\\Mr\\Downloads\\Video\\New folder")
imag_name


['03.jpg', 'girl.jpeg', 'girl02.jpeg', 'rand_arry.png']

In [12]:
imag_name=['03.jpg', 'girl.jpeg', 'girl02.jpeg']



In [13]:
path =r"C:\Users\Mr\Downloads\Video\New folder"
for name in imag_name:
    full_name = os.path.join(path, name)
    #full_name=path + name
    img=cv2.imread(full_name)
    img=cv2.resize(img,(300,200))
    cv2.imshow('girls',img)
    cv2.waitKey(500)
cv2.destroyAllWindows()


## when we press enter image will be changed it depands on waitkey value

In [14]:
import numpy as np
path =r"C:\Users\Mr\Downloads\Video\New folder"
for name in imag_name:
    full_name = os.path.join(path, name)
    #full_name=path + name
    img=cv2.imread(full_name)
    img=cv2.resize(img,(300,200))
    img_02=np.hstack((img))
    img_03=np.vstack((img_02,img_02))
    #img_02=np.hstack((img,img,img))
    #img_03=np.vstack((img_02,img_02,img_02))
    cv2.imshow('girls',img_03)
    cv2.waitKey(0)
cv2.destroyAllWindows()


# vedio play


In [15]:
import numpy as np
import cv2

In [16]:
video_path1=r"C:\\Users\\Mr\Downloads\\Video\\correlation Matrix .mp4"

In [17]:
video_path2=r"C:\\Users\\Mr\\Downloads\\Video\excel tips11.mp4"

In [18]:
cap = cv2.VideoCapture(0)# when you write 0 for your camera 1 or -1 for secondary camera or write name of camera
while cap.isOpened():
     ret,frame=cap.read()
     if ret:
          img=cv2.resize(frame,(300,200))
          cv2.imshow("frame",img)
          if cv2.waitKey(25) & 0xff==ord('q'):
               break
          
     else:
          break
cap.release()
cv2.destroyAllWindows()
     

## single vedio playing

In [ ]:
cap = cv2.VideoCapture(video_path2)
while cap.isOpened():
     ret,frame=cap.read()
     if ret:
          img=cv2.resize(frame,(300,200))
          cv2.imshow("frame",img)
          if cv2.waitKey(25) & 0xff==ord('q'):
               break
          
     else:
          break
cap.release()
cv2.destroyAllWindows()
     

## vedios camera pic paly in single window

In [17]:
import numpy as np
import cv2

video_path1 = r"C:\Users\Mr\Downloads\Video\correlation Matrix .mp4"
video_path2 = r"C:\Users\Mr\Downloads\Video\excel tips11.mp4"
path = r"C:\Users\Mr\Downloads\Video\New folder"
imag_name = "girl.jpeg"

cap1 = cv2.VideoCapture(video_path2)
cap2 = cv2.VideoCapture(video_path1)
cap3 = cv2.VideoCapture(0)

while cap1.isOpened() and cap2.isOpened() and cap3.isOpened():
    ret1, frame1 = cap1.read()
    ret2, frame2 = cap2.read()
    ret3, c_frame = cap3.read()

    if ret1 and ret2 and ret3:
        frame1_resized = cv2.resize(frame1, (300, 200))
        frame2_resized = cv2.resize(frame2, (300, 200))
        c_frame_resized = cv2.resize(c_frame, (300, 200))
        
        img_gil = cv2.imread(path + '\\' + imag_name)
        gil_img_resized = cv2.resize(img_gil, (300, 200))

        frame_first = np.vstack((frame1_resized, frame2_resized))
        frame_2nd = np.vstack((c_frame_resized, gil_img_resized))
        frame_ful = np.hstack((frame_first, frame_2nd))

        cv2.imshow("frame", frame_ful)
        
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break
    else:
        break

cap1.release()
cap2.release()
cap3.release()
cv2.destroyAllWindows()


## imread() patameters

In [25]:
import cv2
image = cv2.imread(r"C:\Users\Mr\Downloads\Video\New folder\girl.jpeg",1)# you can also assign 1 value  resulst will be same colorful imag

img=cv2.resize(image,(300,200))

cv2.imshow('image',img)
print(img)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[221 213 200]
  [221 213 200]
  [221 213 200]
  ...
  [223 218 209]
  [223 218 209]
  [223 218 209]]

 [[221 213 200]
  [221 213 200]
  [221 213 200]
  ...
  [223 218 209]
  [223 218 209]
  [223 218 209]]

 [[221 213 200]
  [221 213 200]
  [221 213 200]
  ...
  [224 219 210]
  [224 219 210]
  [224 219 210]]

 ...

 [[ 88 106 117]
  [ 86 105 113]
  [ 86 105 112]
  ...
  [ 48  68  73]
  [ 51  70  77]
  [ 51  70  77]]

 [[ 96 114 125]
  [ 97 116 124]
  [102 121 127]
  ...
  [ 47  66  73]
  [ 50  69  76]
  [ 50  69  77]]

 [[ 96 115 118]
  [ 94 113 116]
  [ 98 117 120]
  ...
  [ 48  67  80]
  [ 56  75  88]
  [ 52  71  84]]]


## grey scal image
- Reading Images with Transparency: If your image contains an alpha channel for transparency (e.g., PNG images), using -1 ensures that this information is not discarded.

In [28]:
import cv2
image = cv2.imread(r"C:\Users\Mr\Downloads\Video\New folder\girl.jpeg",0)# you can also assign 0 value  resulst will in grey imag

img=cv2.resize(image,(300,200))

cv2.imshow('image',img)
print(img.shape)
print(img)
cv2.waitKey(0)
cv2.destroyAllWindows()


(200, 300)
[[210 210 210 ... 216 216 216]
 [210 210 210 ... 216 216 216]
 [210 210 210 ... 217 217 217]
 ...
 [107 105 105 ...  67  70  70]
 [115 116 121 ...  66  69  69]
 [114 112 116 ...  69  77  73]]


## saving image

In [11]:
import numpy as np
import cv2
import os
rand_array=np.random.randint(255,size=(300,400,3))
cv2.imwrite(r"C:\\Users\\Mr\Downloads\\Video\\New folder\\rand_arry.png",rand_array)#jpg and png both support this fuction
img=cv2.imread(r"C:\\Users\\Mr\Downloads\\Video\\New folder\\rand_arry.png")
cv2.imshow("my image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## we save an image with different format we can also develo a software to change the format of iamge

In [13]:
import cv2
image = cv2.imread(r"C:\Users\Mr\Downloads\Video\New folder\girl.jpeg")# you can also assign 0 value  resulst will in grey imag

img=cv2.resize(image,(300,200))

cv2.imshow('image',img)

cv2.imwrite("girl.png",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## capture and save image from video

In [ ]:
import os
import cv2

path_video = r"C:\Users\Mr\Downloads\Video\excel tips11.mp4"
directory = "Vedio_to_img"

# Create the directory if it doesn't exist
os.makedirs(directory, exist_ok=True)

cap = cv2.VideoCapture(path_video)
img_count = 1

while cap.isOpened():
    ret, frame = cap.read()  # Read the next frame from the video
    if not ret:
        print("Frame is not being read")
        break

    img_path = os.path.join(directory, f"image{img_count}.jpeg")
    is_img_written = cv2.imwrite(img_path, frame)
    if is_img_written:
        print(f"Image {img_count} is saved in folder")

    cv2.imshow('Video', frame)
    if cv2.waitKey(25) & 0xFF == ord('q'):
        break

    img_count += 1

cap.release()
cv2.destroyAllWindows()


## creating video from numpy array

In [24]:
import numpy as np
import cv2
import os
height=700
width=1280
channel=3
fps=30
sec=5
fourcc=cv2.VideoWriter_fourcc(*'MP42')
video=cv2.VideoWriter("vedio.mp4",fourcc,float(fps),(width,height))
for frame_count in range(fps*sec):
    img=np.random.randint(0,255,(height,width,channel),dtype=np.uint8)
    video.write(img)
video.release()

## creating video from images

In [31]:
import numpy as np
import cv2
import os
height=700
width=1280
channel=3
fps=10
sec=5
fourcc=cv2.VideoWriter_fourcc(*'MP42')
video=cv2.VideoWriter("testing.mp4",fourcc,float(fps),(width,height))
#for frame_count in range(fps*sec):
   # img=np.random.randint(0,255,(height,width,channel),dtype=np.uint8)
    #video.write(img)
drictry=r"C:\Users\Mr\Downloads\images"
img_name_list=os.listdir(drictry)
for frame_count in range(fps*sec):
    img_name=np.random.choice(img_name_list)
    img_path=os.path.join(drictry,img_name)
    img=cv2.imread(img_path)
    img_resiz=cv2.resize(img,(width,height))
    video.write( img_resiz)

video.release()