## open cv works with bgr
-he !pip install -q mediapipe command is used to quietly install the mediapipe library in a Jupyter Notebook or any IPython environment. The -q flag suppresses the output to make the installation process cleaner.

In [3]:
import cv2 
import numpy as np
path=  r"C:\Users\Mr\Downloads\images\see2.png"
image=cv2.imread(path)
print(image.shape)
cv2.imshow(" this is road",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(148, 270, 3)


In [4]:
grey_img=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow(" this is road",grey_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [5]:
grey_img# 0 to 255 0 is black and 255 is whilte center values lies between these


array([[24, 25, 26, ..., 25, 26, 27],
       [27, 27, 28, ..., 28, 28, 28],
       [29, 30, 31, ..., 31, 31, 30],
       ...,
       [32, 28, 30, ..., 54, 39, 39],
       [26, 24, 21, ..., 45, 29, 30],
       [21, 22, 13, ..., 35, 19, 21]], dtype=uint8)

In [6]:
grey_img_copy=np.copy(grey_img)
grey_img_copy[grey_img_copy[:,:] <20]=0
cv2.imshow(" this is road",grey_img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
grey_img_copy

array([[24, 25, 26, ..., 25, 26, 27],
       [27, 27, 28, ..., 28, 28, 28],
       [29, 30, 31, ..., 31, 31, 30],
       ...,
       [32, 28, 30, ..., 54, 39, 39],
       [26, 24, 21, ..., 45, 29, 30],
       [21, 22,  0, ..., 35,  0, 21]], dtype=uint8)

In [8]:
grey_img_copy[:,4]

array([ 29,  32,  34,  35,  36,  37,  39,  41,  43,  46,  49,  51,  52,
        54,  57,  60,  63,  72,  80,  81,  64,  30,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  40,  74,
        85,  55,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        22,  33,  36,  35,  33,  29,  25,  21,   0,   0,   0,   0,   0,
         0,  48,  59,  57,  54,  42,  24,  84,  98,  47,  55,  69,  56,
        93,   0, 135, 142, 120, 108,  80,  39,  30,  57,  72,  62,  52,
        62,  64,  71,  79,  84,  84,  84,  85,  96,  72,  64,  70,  73,
        78,  69,  47,  39,  49,  50,  37,  26,  25,  26,  25,  24,  31,
        34,  23,  23,  34,  29,  20,  31,  34,  34,  30,  29,  30,  31,
        29,  29,  27,  25,  25], dtype=uint8)

In [9]:
img_cop= np.copy(image)
img_cop.shape

(148, 270, 3)

In [ ]:
import cv2
import numpy as np

path=  r"C:\Users\Mr\Downloads\images\see2.png"
image=cv2.imread(path)
img_cop= np.copy(image)
mask=img_cop[(img_cop[:,:,0]<50)|(img_cop[:,:,1]<50)|(img_cop[:,:,2]<89)]=255
img_cp2=np.hstack(cv2.resize(image,(600,400)),cv2.resize(mask,(600,400)))
cv2.imshow(" this is road",img_cp2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [22]:
import cv2
import numpy as np
path = r"C:\Users\Mr\Downloads\images\see2.png"
image = cv2.imread(path)
img_cop = np.copy(image)
mask = (img_cop[:,:,0] < 50) | (img_cop[:,:,1] < 50) | (img_cop[:,:,2] < 50)

img_cop[mask] = 255
image_resized = cv2.resize(image, (600, 400))
mask_resized = cv2.resize(img_cop, (600, 400))

# Stack the original and masked images horizontally
img_cp2 = np.hstack((image_resized, mask_resized))

# Display the stacked image
cv2.imshow("this is road", img_cp2)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
import cv2
import numpy as np
path = r"C:\Users\Mr\Downloads\images\see.png"
image = cv2.imread(path)
image=cv2.resize(image,(500,300))
cv2.imshow("this is road", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


## blure image using 3*3 kernal

In [5]:
ones_mat_3_3 = np.ones((3, 3), dtype=np.float32)/9

imag_blur_3_3=cv2.filter2D(image,-1,ones_mat_3_3)#-1 parameter in cv2.filter2D specifies that the depth (or number of channels) 
cv2.imshow("blur image 3*3",imag_blur_3_3)
cv2.imshow("orignal",image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [6]:
ones_mat_5_5 = np.ones((5, 5), dtype=np.float32)/25

imag_blur_5_5=cv2.filter2D(image,-1,ones_mat_5_5)#-1 parameter in cv2.filter2D specifies that the depth (or number of channels) 
cv2.imshow("blur image 3*3",imag_blur_3_3)
cv2.imshow("orignal",image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [7]:
ones_mat_10 = np.ones((10, 10), dtype=np.float32)/100

imag_blur_10=cv2.filter2D(image,-1,ones_mat_10)#-1 parameter in cv2.filter2D specifies that the depth (or number of channels) 
cv2.imshow("blur image 3*3",imag_blur_10)
cv2.imshow("orignal",image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [10]:
ones_mat_100 = np.ones((100, 100), dtype=np.float32)/10000

imag_blur_100=cv2.filter2D(image,-1,ones_mat_100)#-1 parameter in cv2.filter2D specifies that the depth (or number of channels) 
cv2.imshow("blur image 3*3",imag_blur_100)
cv2.imshow("orignal",image)
cv2.waitKey(0)
cv2.destroyAllWindows()


## all  iamges in one sucreen

In [11]:


import cv2
import numpy as np

# Load your image
image = cv2.imread(path)

# Function to create a blur kernel of a given size
def create_blur_kernel(size):
    return np.ones((size, size), dtype=np.float32) / (size * size)

# List of kernel sizes for different blurs
kernel_sizes = [3, 5, 7, 15, 25]

# List to store the blurred images
blurred_images = []

# Apply different blurs to the image
for size in kernel_sizes:
    kernel = create_blur_kernel(size)
    blurred_image = cv2.filter2D(image, -1, kernel)
    blurred_images.append(blurred_image)

# Concatenate images horizontally
all_blurred = cv2.hconcat(blurred_images)

# Display the concatenated image
cv2.imshow('Blurred Images', all_blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()


## blur teachniques 
- averaging
- Gaussian Blurring:reducing high-frequency noise.
- Median Blurring:
- Bilateral Filtering:
  This technique is highly effective in noise removal while keeping edges sharp.
- Box Filter:
      This is similar to the averaging blur but allows the depth of the output image to be controlled.

In [12]:
import cv2
import numpy as np
path = r"C:\Users\Mr\Downloads\images\the.png"
image = cv2.imread(path)
image=cv2.resize(image,(500,300))
cv2.imshow("this is road", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


# blur image with cv2.bure()

In [14]:
blur_img=cv2.blur(image,(3,3))# you can apply this with different parameters
cv2.imshow("this is road", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
box_img=cv2.boxFilter(image,-1,(25,25),normalize=True)# you can apply this with different parameters
cv2.imshow("this is road", box_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
import cv2
import numpy as np
path = r"C:\Users\Mr\Downloads\images\boy.jpeg"
image = cv2.imread(path)
image=cv2.resize(image,(500,300))
cv2.imshow("this is road", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [26]:
#imag_gu5=cv2.GaussianBlur(image,(5,5),0)# 0 is sigma value,It directly affects the amount of blurring applied to the image.
#imag_gu7=cv2.GaussianBlur(image,(7,7),1)
imag_gu9=cv2.GaussianBlur(image,(9,9),2)
imag_gu11=cv2.GaussianBlur(image,(11,11),sigmaX=13,sigmaY=40)# sigma y strech image to y diretion
#cv2.imshow("this is road", imag_gu5)
#cv2.imshow("this is road", imag_gu7)
#cv2.imshow("this is road", imag_gu9)
cv2.imshow("this is road", imag_gu11)
cv2.waitKey(0)
cv2.destroyAllWindows()