In [ ]:
import cv2
import numpy as np


## morphological operation
- erosion
- dilation
- opening
- closing
- morphological gradient
- top hat
- black hat



### in erosion method white pixel will decrese removal of noise
### object will shrink

In [13]:
path=r"C:\Users\Mr\Downloads\images\the.png"
image=cv2.imread(path,0)# load image in gray scale
image=cv2.resize(image,(500,300))
kernel = np.ones((7, 7), np.uint8)# filter
eroded_image = cv2.erode(image, kernel, iterations=1)
act_erod_img=np.hstack((image,eroded_image))
cv2.imshow("this is orginal",act_erod_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## dilation oposit to erosion
## it increase white pixels

import cv2
import numpy as np

path=r"C:\Users\Mr\Downloads\images\the.png"
image=cv2.imread(path,0)# load image in gray scale
image=cv2.resize(image,(500,300))
kernel = np.ones((7, 7), np.uint8)# filter
dilat_image = cv2.dilate(image, kernel, iterations=1)
act_dilat_img=np.hstack((image,dilat_image))
cv2.imshow("this is orginal",act_dilat_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [4]:
import cv2
import numpy as np
path=r"C:\Users\Mr\Downloads\images\fruit.png"
imag=cv2.imread(path)
print(imag.shape)
imag=cv2.resize(imag,(int(imag.shape[1]*0.5),int(imag.shape[0] * 0.5)))# for half oixels of iamg

cv2.imshow("window",imag)
cv2.waitKey(0)
cv2.destroyAllWindows()

(492, 640, 3)


In [4]:
imag.shape

(246, 320, 3)

In [5]:
246*320 #total pixels,rows of image is height and cols are width

78720

In [6]:
imag.size

236160

## access single pixel

In [7]:
imag[0,0]

array([0, 0, 0], dtype=uint8)

In [8]:
imag[0,0,0],imag[0,0,1],imag[0,0,2]# access channels

(0, 0, 0)

In [9]:
imag[0,0,2]

0

In [10]:
imag[0][0]# access zero and at 0 pont

array([0, 0, 0], dtype=uint8)

In [5]:
imag[130,120]

array([  0, 141, 224], dtype=uint8)

## showing single pixel as an image

In [7]:
cv2.imshow("window",imag[130,120])
cv2.waitKey(0)
cv2.destroyAllWindows()

## acess single row

In [ ]:
imag[100]# access single row at 100 index 

In [13]:
imag[100,:]# same result with slicing method its hows color pixcel value

array([[  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [ 16, 123, 121],
       [ 12, 194, 255],
       [  0, 177, 250],
       [  0, 182, 252],
       [ 11, 189, 249],
       [ 43, 207, 244],
       [ 93, 223, 244],
       [ 91, 225, 244],
       [ 99, 226, 244],
       [108, 228, 243],
       [137, 229, 240],
       [158, 230, 239],
       [159, 227, 235],
       [146, 222, 231],
       [169, 225, 234],
       [126, 202, 233],
       [ 56, 184, 237],
       [ 54, 170, 230],
       [  0, 139, 227],
       [  9, 134, 229],
       [ 61, 147, 234],
       [191, 207, 241],
       [248, 240, 245],
       [220, 234, 254],
       [187, 215, 252],
       [167, 199, 252],
       [105, 172, 243],
       [  6, 147, 230],
       [  0, 140, 224],
       [  0, 137, 223],
       [ 12, 141, 223],
       [116, 195, 245],
       [190, 224

In [9]:
imag[0].shape

(320, 3)

In [16]:
imag[100,:,1]#by default it acces all channels but we can assign chanel value

array([  0,   0,   0,   0,   0,   0,   0,   0,   0, 123, 194, 177, 182,
       189, 207, 223, 225, 226, 228, 229, 230, 227, 222, 225, 202, 184,
       170, 139, 134, 147, 207, 240, 234, 215, 199, 172, 147, 140, 137,
       141, 195, 224, 190, 176, 173, 188, 168, 165, 170, 170, 196, 179,
       162, 157, 164, 206, 174, 185, 209, 172, 163, 148, 159, 155, 172,
       177, 164, 202, 165, 143, 179, 160, 181, 153, 165, 169, 210, 156,
       225, 209, 167, 147, 179, 183, 168, 158, 164, 167, 171, 204, 196,
       203, 176, 172, 168, 159, 201, 170, 159, 144, 159, 196, 219, 156,
       141, 150, 172, 144, 147, 137, 148, 147, 169, 193, 184, 170, 175,
       186, 197, 151, 132, 155, 157, 151, 163, 153, 150, 187, 168, 172,
       170, 167, 157, 153, 151, 151, 187, 161, 159, 166, 171, 175, 175,
       177, 163, 166, 190, 145, 167, 171, 151, 168, 158, 160, 185, 171,
       183, 184, 166, 173, 179, 169, 170, 148, 182, 177, 147, 163, 170,
       177, 180, 160, 162, 161, 166, 173, 183, 187, 181, 195, 19

## we can change chanel value to change imag

In [18]:
cv2.imshow("window",imag[:,:,(2,1,0)])# these three values can change
cv2.waitKey(0)
cv2.destroyAllWindows()

## access whole rows and single col

In [20]:
imag[:,200,(1,2)].shape

(246, 2)

In [1]:
import cv2
import numpy as np
path=r"C:\Users\Mr\Downloads\images\fruit.png"
imag=cv2.imread(path)
print(imag.shape)
imag=cv2.resize(imag,(int(imag.shape[1]*0.5),int(imag.shape[0] * 0.5)))# for half oixels of iamg

cv2.imshow("window",imag)
cv2.waitKey(0)
cv2.destroyAllWindows()

(492, 640, 3)


## access the part of image

In [5]:
imag[67:100,50:110] #   imag[y1:y2,x1:x2]y1=100,x1=67,y2=200,x2=220
cv2.imshow("window",imag[67:100,50:110])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
imag[110:150,70:130] #   imag[y1:y2,x1:x2]y1=100,x1=67,y2=200,x2=220
cv2.imshow("window",imag[110:150,70:130])
cv2.imwrite("part of img.jpg",imag[110:150,70:130])#save image
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
for i in range(imag.shape[0]):# access one row and all cols
    cv2.imshow("image",imag[0:i+1,:])
    if cv2.waitKey(0) &0xff==ord('q'):
       break
cv2.destroyAllWindows()



In [20]:
for i in range(imag.shape[1]): #access one row and all cols
    cv2.imshow("image",imag[:,0:i+1])
    if cv2.waitKey(0) &0xff==ord('q'):
       break
cv2.destroyAllWindows()



# add color pixel in image

In [1]:
import cv2
import numpy as np
import time
import random

In [2]:
path=r"C:\Users\Mr\Downloads\images\boy.jpeg"
img=cv2.imread(path)
cv2.imshow("window",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# add new single color piXel in an image

In [25]:
img[0][0]# at zero row pixel color value

array([106, 100, 101], dtype=uint8)

In [28]:
img_cop=img.copy()
img_cop[0][0]=np.array([255,255,255])
img_cop[0][1]=np.array([0,0,0])
img_cop[0][2]=np.array([0,0,255])
img_cop[0][3]=np.array([0,255,0])
img_cop[0][0]=np.array([255,0,0])
cv2.imshow("image",img_cop)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [ ]:
import cv2
import numpy as np
import time
import random
path=r"C:\Users\Mr\Downloads\images\fruit.png"
img=cv2.imread(path)
img_cop=img.copy()
img_width=img_cop.shape[1]
img_height=img_cop.shape[0]
print(img_width)
print(img_height)
for col_indx in range(img_width):
               if col_indx%2==0:
                   img_cop[0][col_indx]=np.array([0,0,0])
                   img_cop[1][col_indx]=np.array([0,0,255])
                   img_cop[2][col_indx]=np.array([0,255,0])
                   img_cop[3][col_indx]=np.array([0,255,255])
                   img_cop[4][col_indx]=np.array([255,0,0])
                   img_cop[5][col_indx]=np.array([0,0,0])
                   img_cop[6][col_indx]=np.array([0,0,255])
                   img_cop[7][col_indx]=np.array([0,255,0])
                   img_cop[9][col_indx]=np.array([0,255,255])
                   img_cop[4][col_indx]=np.array([255,0,0])
                   cv2.imshow("image",img_cop)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [7]:
import cv2
import numpy as np
import time
import random
path=r"C:\Users\Mr\Downloads\images\fruit.png"
img=cv2.imread(path)
img_cop=img.copy()
img_width=img_cop.shape[1]
img_height=img_cop.shape[0]
print(img_width)
print(img_height)
for row_indx in range(img_height):
         for col_indx in range(img_width):
               #if col_indx%2==0:
               #if col_indx%5==0:
                if col_indx%15==0:
                   img_cop[row_indx][col_indx]=np.array([255,255,0])
                   
cv2.imshow("image",img_cop)
cv2.waitKey(0)
cv2.destroyAllWindows()


640
492


In [ ]:
import cv2
import numpy as np
import time
import random
path=r"C:\Users\Mr\Downloads\images\fruit.png"
img=cv2.imread(path)
img_cop=img.copy()
img_width=img_cop.shape[1]
img_height=img_cop.shape[0]
print(img_width)
print(img_height)
for row_indx in range(img_height):
    #if row_indx%2==0:
    if row_indx%15==0:
         for col_indx in range(img_width):
               #if col_indx%2==0:
               #if col_indx%5==0:
                if col_indx%15==0:
                   img_cop[row_indx][col_indx]=np.array([255,255,0])
                   
cv2.imshow("image",img_cop)
cv2.waitKey(0)
cv2.destroyAllWindows()


## add new  random color pixel randomly in image

In [2]:
import cv2
import numpy as np
import time
import random
path=r"C:\Users\Mr\Downloads\images\fruit.png"
img=cv2.imread(path)
img_cop=img.copy()
img_width=img_cop.shape[1]
img_height=img_cop.shape[0]
print(img_width)
print(img_height)
for row_indx in range(img_height):
    #if row_indx%2==0:
    if row_indx%15==0:
         for col_indx in range(random.randint(0,600)):
               #if col_indx%2==0:
               #if col_indx%5==0:
                if col_indx%15==0:
                   b_random=random.randint(0,255)
                   g_random=random.randint(0,255)#g_random=np.random.randint(0,25) same funtion
                   r_random=random.randint(0,255)
                   img_cop[row_indx][col_indx]=np.array([b_random,r_random,g_random])
                   
cv2.imshow("image",img_cop)
cv2.waitKey(0)
cv2.destroyAllWindows()


640
492


## add new color pixel in portion or any location

In [ ]:
#Importing opencv
import cv2

# instance of video capture
cap = cv2.VideoCapture(0)

#Checking if the camera is opened or not
opened = cap.isOpened()

#fourcc - four character code for determining the codec of the video file
fourcc = cv2.VideoWriter_fourcc(*'MJPG')


#Getting the properties of the video using video capture instance
height = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
width = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
fps = cap.get(cv2.CAP_PROP_FPS)

# output video writer creation
out = cv2.VideoWriter('my_video.avi', fourcc,fps ,(int(width), int(height)))

print("Frames are {}".format(fps))


#Showing and storing the live camera feed
#Check if camera is opened
if(opened):
	#Run until it remains open
	while(cap.isOpened()):
		#Get the frame from Video capture Instance
		ret, frame = cap.read()
		#
		#return ret Variable tells if the frame is returned successfully
		if(ret==True):
			cv2.imshow('winname', frame)
			#Writing the frame to video output
			out.write(frame)
			#Wait for 2 milliseconds for each frame 
			#If user press 'esc' key then exit loop
			if(cv2.waitKey(2)==27):
				break
out.release()
cap.release()
cv2.destroyAllWindows()